[package]
name = "realm"
version = "2.5.1"
authors = ["zhboner <zhboner@gmail.com>"]
edition = "2021"


[workspace]
members = [
    "realm_io",
    "realm_lb",
    "realm_core",
    "realm_hook",
    "realm_syscall"
]


[lib]
name = "realm"
path = "src/lib.rs"

[[bin]]
name = "realm"
path = "src/bin.rs"


[dependencies]
# realm
realm_core = { path = "realm_core" }

# common
cfg-if = "1"
futures = "0.3"

# runtime
tokio = { version = "1", features = ["rt"] }

# logger
log = "0.4"
fern = "0.6"
chrono = "0.4"

# command
clap = "3.1"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# malloc
mimalloc = { version = "0.1", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5", optional = true }
mmap-allocator = { version = "0.3", optional = true }


[dev-dependencies]
env_logger = "0.10"
tokio = { version = "1", features = ["macros"] }


[features]
default = ["hook", "proxy", "balance", "multi-thread", "transport", "brutal-shutdown" ]
hook = ["realm_core/hook"]
proxy = ["realm_core/proxy"]
brutal-shutdown = ["realm_core/brutal-shutdown"]
balance = ["realm_core/balance"]
transport = ["realm_core/transport", "realm_core/transport-boost"]
multi-thread = ["tokio/rt-multi-thread"]
jemalloc = ["jemallocator"]
mi-malloc = ["mimalloc"]
page-alloc = ["mmap-allocator"]


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
incremental = false
panic = "unwind"
strip = true
