[package]
name = "realm"
version = "0.1.0"
authors = ["zhboner <zhboner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
trust-dns-resolver = "*"
futures = "0.3"
structopt = "0.3.14"