[log]
level = "warn"
output = "/var/log/realm.log"

[dns]
mode = "ipv4_only"
protocol = "tcp_and_udp"
nameservers = ["8.8.8.8:53", "8.8.4.4:53"]
min_ttl = 600
max_ttl = 3600
cache_size = 256

[network]
use_udp = true
zero_copy = true
fast_open = true
tcp_timeout = 300
udp_timeout = 30
send_proxy = true
send_proxy_version = 2
accept_proxy = true
accept_proxy_timeout = 5

[[endpoints]]
listen = "0.0.0.0:5000"
remote = "1.1.1.1:443"
through = "0.0.0.0"
interface = "lo"

[[endpoints]]
listen = "0.0.0.0:10000"
remote = "www.google.com:443"
through = "0.0.0.0"
interface = "wlan0"
