name: build
on:
  push:
    paths-ignore: ["**.md"]
    branches: [master, nightly]
  pull_request:
    paths-ignore: ["**.md"]
    branches: [master]

jobs:
  build:
    runs-on: >-
      ${{  
        contains(matrix.target, 'apple') && 'macos-latest' ||
        contains(matrix.target, 'windows') && 'windows-latest' ||
        'ubuntu-22.04'
      }}
    strategy:
      matrix:
        target:
          # cross
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-gnu
          - x86_64-linux-android
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - aarch64-linux-android
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-musleabihf
          - armv7-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabi
          - armv7-unknown-linux-musleabihf
          # mips
          - mips-unknown-linux-gnu
          - mips-unknown-linux-musl
          - mipsel-unknown-linux-gnu
          - mipsel-unknown-linux-musl
          - mips64-unknown-linux-gnuabi64
          - mips64-unknown-linux-muslabi64
          - mips64el-unknown-linux-gnuabi64
          - mips64el-unknown-linux-muslabi64
          # windows
          - x86_64-pc-windows-msvc
          # apple
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - aarch64-apple-ios
    steps:
      - uses: actions/checkout@v6
      - run: mkdir -p out/${{ matrix.target }}
      # cross
      - name: build cross
        if: |
          !contains(matrix.target, 'mips') &&
          !contains(matrix.target, 'apple') &&
          !contains(matrix.target, 'windows')
        uses: ./.github/actions/build/cross
        with:
          target: ${{ matrix.target }}
          outdir: out/${{ matrix.target }}
      # mips
      - name: build mips
        if: contains(matrix.target, 'mips')
        uses: ./.github/actions/build/mips
        with:
          target: ${{ matrix.target }}
          outdir: out/${{ matrix.target }}
      # windows
      - name: build windows
        if: contains(matrix.target, 'windows')
        uses: ./.github/actions/build/windows
        with:
          target: ${{ matrix.target }}
          outdir: out/${{ matrix.target }}
      # apple
      - name: build apple
        if: contains(matrix.target, 'apple')
        uses: ./.github/actions/build/apple
        with:
          target: ${{ matrix.target }}
          outdir: out/${{ matrix.target }}
      # finalize
      - name: upload binary
        uses: actions/upload-artifact@v6
        with:
          name: realm-${{ matrix.target }}
          path: out/${{ matrix.target }}/realm
      - name: upload binary (slim)
        uses: actions/upload-artifact@v6
        with:
          name: realm-slim-${{ matrix.target }}
          path: out/${{ matrix.target }}/realm-slim
